### PR TITLE
build rpm package the same way paho-c does

### PR DESCRIPTION
**Pull request by jcourtat**
Hello, 

This patch adds build of rpm

Thanks for reviewing

Julien

### CODE REVIEW

**Comment by jcourtat** [comment]
what a pain to register eclipse!
fill the form, find a new 12 chars long password (i would suggest 32 chars long), fail for 6 captcha, check all boxes with "ok i don't understand a thing but now i'm sure my firm will be hunted by America's doj", confirm the email, 3 faileds captcha again and now
i don't know what to do to trigger a review.
can you help.

**Comment by fpagliughi** [comment]
It's saying that you don't have a signed Eclipse Contributor Agreement (ECA).

**Comment by jcourtat** [comment]
i registered an ECA, but anyway,  i have some question about cmake.
on centos/redhat, cmake has version 2.8.x and paho-cpp requires a more recent version. cmake3 package does the job but imposes to call cmake3 command instead of cmake, does that sound bad to you ?

**Comment by fpagliughi** [comment]
We originally tried getting the build to work with CMake 2.x, but there were too many issues with C++11. So we gave up and set the requirement at a minimum of 3.1.

In the project README.md, I describe updating CMake on Ubuntu systems by installing a recent 3.x version as the system default CMake, and relegating the old version to run as `cmake-2.82. See:
https://github.com/eclipse/paho.mqtt.cpp#updating-cmake-on-ubuntu-1404--mint-17-lts

That has worked great for me on my machines, as the backward compatibility has not been an issue, and it helps with other libraries that require CMake 3.x. But you can do whatever works best for you on your system.

**Pull request closed without merging**
