### PR TITLE
Fix C++11 compatibility

### PR DESCRIPTION
**Pull request by rpoisel**
Sorry for the inconvenience with my last commit - this should fix it. I have tried it with GCC 8.2 on Linux x64.

### CODE REVIEW

**Comment by rpoisel** [comment]
I am suprised that you did not have any problems with this setting. I was using the g++ compiler (version 8.2) for the raspberry pi platform using the `-std=gnu++17` (it might also have been `-std=c++17`) compiler flag.
If you want, I can provide you with my build log. But this will take some time (hours) because I am away from my development environment at the moment.

**Comment by rpoisel** [comment]
Ahhh ... maybe I should have mentioned: I experienced the problems when *using* the library in C++17 code - not during the build.

Because of the symbol being defined both in the binary as well as by what's stated within the header file.

Maybe we should make the symbol `const` instead of `constexpr`? This would ensure, that it has to be defined in the .cpp file.

**Comment by rpoisel** [comment]
To be honest, I don't get the reasoning behind having some class constants `constexpr` and some others `const` (see [paho.mqtt.cpp/src/mqtt/message.h](https://github.com/eclipse/paho.mqtt.cpp/blob/master/src/mqtt/message.h)).

I would suggest having them all `const` because this assures that the symbol is to found *once* only in the Paho CPP library - also in C++17.

**Comment by fpagliughi** [comment]
OK. If an application won’t link against the library, that would be a bug. I’ll have a look.

As for const vs constexpr, that may be a good solution. They’re mixed in the library because it’s been around for some years with different contributors, and styles have been changing as the language changes,

**Comment by rpoisel** [comment]
Thanks for your quick response!

If you want, I can update this pull-request to not use preprocessor directives but const in all places that at least would affect C++17 compatibility.

**Comment by fpagliughi** [comment]
My plan is to first write a Travis/CI test that would include some newer compilers and C++ standards so that it would catch this error (perhaps when linking the unit test app).

Then we can start exploring fixes - and run regression tests to make sure that they don't cause problems with other supported setups.

I've already started reworking the tests. I will add this in.

**Comment by fpagliughi** [comment]
@rpoisel Thanks again for this PR. Sorry for the long delay. There were a bunch of new constexpr, and some conflicts, so I went through and added this manually.

**Pull request closed without merging**
