### PR TITLE
Modernize the build system

### PR DESCRIPTION
**Pull request by dawagner**
Modernize the CMake build system, including the generation and installation of a CMake package configuration file. This will make it easier for CMake-enabled projects to use paho.mqtt.cpp: they'll just have to call `find_package(PahoMqttCpp)` and then have their targets link against `PahoMqttCpp::paho-mqttpp3`.

Also, remove the other build systems because maintaining multiple build systems is painful.

### CODE REVIEW

**Comment by dawagner** [comment]
TODO: tests are not run in the CI when using CMake.

**Comment by dawagner** [comment]
BTW, tests (and therefore the CI) are currently broken in master: they segfault.

**Comment by dawagner** [comment]
A fix for the tests has been submitted at #149.

**Comment by dawagner** [comment]
Any thought on this? If you're not comfortable with removing the other build systems, it is done in a standalone commit and can easily be dropped.

**Comment by fpagliughi** [comment]
Hey, sorry. Haven't had time to look at anything this week. My plan was to dump autotools before the next release, and to push CMake as the default build tool. But I do use the Makefile in development, so wasn't planning on getting rid of it any time soon.
I also have a number of uncommitted modifications to the CMae files, so may need to look at merging everything. I'll have a look at this in the next few days.

**Comment by fpagliughi** [comment]
Hey, sorry. Haven't had time to look at anything this week. My plan was to dump autotools before the next release, and to push CMake as the default build tool. But I do use the Makefile in development, so wasn't planning on getting rid of it any time soon.
I also have a number of uncommitted modifications to the CMae files, so may need to look at merging everything. I'll have a look at this in the next few days.

**Comment by fpagliughi** [comment]
@dawagner , I'm having trouble cherry-picking and testing the individual parts of this PR. Could you rebase this to the develop branch and re-submit as separate PR's.

**Comment by dawagner** [comment]
@fpagliughi This PR now only contains the CMake modernization. I can't submit independent PRs for removing the autotools because it would conflict with this one but I'll send two more PRs based on this one.

**Comment by fpagliughi** [comment]
@dawagner Thanks for the rework. Don't worry about removing the autotools stuff. I should announce the deprecation before removing it anyway. I can get the files out at the appropriate time. I'm mostly interested in moving CMake forward, and there's some good stuff in your PR.

The thing I want to be careful of is that people (like you and me) who may be working on the Paho C and C++ libraries simultaneously can operate efficiently.

I have a bunch of uncommitted CMake updates as well, but I will look to check out your stuff first and get it in before merging what I've done. And I'm not a CMake master, so I will likely put the new stuff up in a branch so that people can comment first.

But I'm up against two looming deadlines. First I need to get a bug fix v1.0.1 out ASAP, with few big changes. Then I need to get updates for MQTT v5 done by the end of next month. So the build tools need to be stabilized quickly!

**Comment by Croydon** [comment]
Any updates on this?

**Comment by fpagliughi** [comment]
Merged into `develop`

**Comment by dawagner** [comment]
Thanks :)

**Pull request closed without merging**
