### PR TITLE
Use MQTTAsync_strerror to provide meaningful error messages

### PR DESCRIPTION
**Pull request by dawagner**
Signed-off-by: David Wagner <david.wagner@easymile.com>

### CODE REVIEW

**Comment by dawagner** [comment]
This requires a commit in paho.mqtt.c that was recently merged in the develop branch (hence the CI failure).

**Comment by fpagliughi** [comment]
Sorry, I meant to write a while ago...
This looks cool. I'll get it in when we move to a version that wraps Paho C v1.3.

**Comment by fpagliughi** [comment]
I'm going to squeak out a bug fix release shortly (v1.0.1). This won't make it into that release, but will surely go into the next one (v1.1).

**Comment by fpagliughi** [comment]
Thanks again for the PR. 
Sorry. I had forgotten about this. I merged it with a couple mods.

**Pull request merged**
