### PR TITLE
Ios build

### PR DESCRIPTION
**Pull request by a4z**
required changes for #249
make paho.mqtt.cpp build also on iOS

### CODE REVIEW

**Comment by a4z** [comment]
I hope this works now I see a "You successfully submitted an Eclipse Contributor Agreement." on my eclipse account page, but I don't know what to do if the eclipsefdn/eca  fails again .....

**Comment by fpagliughi** [comment]
Hey. Thanks for the contribution. Yes, I'm seeing that the ECA was signed, so no worries there.

**Comment by fpagliughi** [comment]
I want to make sure that Mac/iOS is supported, and since I don't own a Mac, I really appreciate you sending this.

I'm curious about 88452c99, though. When choosing both static and shared libraries, this will build each source file twice: once for each library type. Does iOS require different compile options for static and shared libraries? Does this handle that situation?

I was thinking I might need to do this for Windows if I tried locking down export headers to be more specific. But I didn't want to slow down the Linux build to do so.

**Comment by a4z** [comment]
unfortunately, yes, this means, if you build both, static and dynamic libraries, it will compile the files twice 

an alternative would be, a huge if iOS branch, and handle this in the if branch
shall I do that? 
I thought about that for a moment when doing the 
but did not do it because the use cases where both will be build seem to me limited 

but it would not be super difficult to add, just make the CMakeLists.txt a bit more complex

**Comment by a4z** [comment]
@fpagliughi  , here is an alternative implementation, it has some more if (...) 

https://github.com/a4z/paho.mqtt.cpp/blob/ios_build_1/src/CMakeLists.txt

but if you would like that more, I can update this PR with that approach

**Comment by a4z** [comment]
Hi @fpagliughi , sorry for pinging you, 
but I am creating a conan package for ios android (which I will also push to the index center) and I need to add  a patch of the change. 
did you have time to check the alternative approach, and decide which one you prefer? 
I have a working version , so I can proceed anyway, but just thought, if we agree on an implementation and I have the 'final' patch, this would be nice

**Comment by fpagliughi** [comment]
I'm at a customer site this week, so probably won't have time to test anything until the weekend.

**Comment by a4z** [comment]
ok, thanks for letting me know!

**Comment by a4z** [comment]
turned out, it seems, the object library does not need to be replaced, 
only the 'help finding pthread on iOS' is mandatory for iOS.
Will submit that after having done more testing

**Comment by a4z** [comment]
sorry, this was wrong to close this one, still needed :-) and paho-mqtt-c needs the same fix, since it is using object libraries in the same way, but there the cmake file is slightly more complicated

**Comment by a4z** [comment]
additional info, just in case someone wonders why I open/closed this

there seem to be some things in CMake going on, e.g. https://gitlab.kitware.com/cmake/cmake/issues/20036

also, find library needs some help on iOS , giving 
`-DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=BOTH -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=BOTH -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=NEVER` to cmake seems to fix the findthread part.

so until all this cmake issues are sorted out, I will not commit any CMake related fixes that are no 110% confirmed to be a problem of the CMakefile

**Pull request closed without merging**
