### PR TITLE
Use "override" instead of "virtual" for inherited member functions

### PR DESCRIPTION
**Pull request by guilhermeferreira**
Using "override" for inherited member functions. This keyword provides better check than virtual.

### CODE REVIEW

**Comment by guilhermeferreira** [comment]
This is a very low risk change. It simply reinforces function overriding check and do not impose run-time problems.

**Comment by guilhermeferreira** [comment]
Would like me to rebase this branch?

**Comment by fpagliughi** [comment]
Sure, that might fix the problem quickly enough, although I just figured out what happened. Apparently when I used the online tool to resolve the small merge conflict, the Eclipse validator saw the author of the merge commit as "noreply@github.com" and flagged that user as not having an ECA!

**Comment by guilhermeferreira** [comment]
Done @fpagliughi! Could you please double check if my conflict resolution is correct?

**Comment by fpagliughi** [comment]
Sorry I hadn't realized that there was a reorganization of the token files included in this pull request. Those played havoc with two other branches I've been considering, so for now, I just cherry-picked commit b07f493dbd0b49346faeaecacab6fd17d4f0869b to add the override keywords.
Perhaps we can consider file reorganization in separate, dedicated issues/pull requests.

**Comment by guilhermeferreira** [comment]
I guess you cherry-picked the commit c96e2ffd (which became 21dba926 at master) instead of the commit b07f493. Anyway, those classes separation are not necessary anymore because the token interfaces (`itoken` and `idelivery_token`) have been removed in commit 46917ab7.

**Comment by fpagliughi** [comment]
Yes, that looks like what I did! I'm happy with the overall resolution of this. Let me know if I missed anything.

**Comment by guilhermeferreira** [comment]
So far so good. I made the comment just to keep a record.

**Pull request closed without merging**
